### ISSUE TITLE
androidNative target support

### ISSUE THREAD

**Issue by penn5** [korlibs/easy-kotlin-mpp-gradle-plugin#5]
The androidNative\<arch> cross-compilation target is not implemented.

**Comment by soywiz** [comment]
Just curious. Why do you want this when you have a pure Java Android target that covers all the supported architectures? (mips, arm64, arm32, x64...)

**Comment by penn5** [comment]
Because you can't use pure java outside java? E.g. using kotlin native?

**Comment by penn5** [comment]
Isn't the whole point of kotlin multiplatform that you can have multiple platforms?

**Comment by soywiz** [comment]
For Korge I don't need it. I mean: makes sense to create native executables for desktop (no dependencies, fast startup and less memory). But an APK is already a native executable on Android. Adding native there and supporting all the architectures, would increase the APK size or limit the number of devices where you can run the APP. That's why I didn't add it. You can use JNA to call native code from Kotlin on Android, and I didn't needed it for korge either.

Still if it is useful for you, I can add something like a property `enable.android.native=true` as an opt-in. That would work for you?

**Comment by penn5** [comment]
But this plugin is used when publishing, say, krypto? So krypto is incompatible with androidNative

**Comment by soywiz** [comment]
I see. Do you know any project using android native at this point? If it is the case I can publish some libraries with android native support.
The problem is also that each platform I add, times and artifact since are growing a lot. So I expend several days when a new version of Kotlin is released due to Kotlin/Native ABI incompatibilities since I have to recompile all the projects. Hopefully with Kotlin 1.4, there will be just one .klib artifact and will work on all the platforms if it contains common code.

**Comment by penn5** [comment]
Well, I'm using androidNative!

**Comment by soywiz** [comment]
Which libraries are you using? `krypto`? any other? (I can compile only those, so the rest of the projects doesn't take that much time)

**Comment by penn5** [comment]
Just krypto, yeah

**Comment by soywiz** [comment]
1.11.0:

* https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/krypto/krypto-androidnativex86/1.11.0/
* https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/krypto/krypto-androidnativex64/1.11.0/
* https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/krypto/krypto-androidnativearm32/1.11.0/
* https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/krypto/krypto-androidnativearm64/1.11.0/

**Comment by penn5** [comment]
Thanks!
